// Alle zichtbare teksten (UX-01). Geen "relay", "HLC" of "Nostr" buiten het instellingenscherm (UX-06).
import type { CategoryId } from '../core/types';

export const strings = {
  appName: 'BOODSCHAP!',
  loading: 'Even geduld…',
  startError: 'BOODSCHAP! kon niet starten.',
  retry: 'Opnieuw proberen',
  defaultListName: 'Boodschappen',
  sharedListPlaceholderName: 'Gedeelde lijst',
  shareWarning: 'Deel deze code alleen met mensen die je vertrouwt. Wie de code heeft, kan altijd meedoen.',

  // Overzicht
  listsTitle: 'Lijsten',
  newList: 'Nieuwe lijst',
  addSharedList: 'Lijst toevoegen',
  settings: 'Instellingen',
  newListPlaceholder: 'Naam van de lijst',
  create: 'Maken',
  cancel: 'Annuleren',
  save: 'Opslaan',
  shared: 'Gedeeld',
  progress: (checked: number, total: number) => `${checked} van ${total} afgevinkt`,
  emptyItemsCount: 'Nog leeg',
  listsEmptyTitle: 'Nog geen lijsten',
  listsEmptyBody: 'Maak een nieuwe lijst of voeg een gedeelde lijst toe.',

  // Lijstscherm
  addPlaceholder: 'Wat moet er in huis?',
  add: 'Toevoegen',
  listEmptyTitle: 'Je lijst is leeg',
  listEmptyBody: 'Typ hieronder wat je nodig hebt, bijvoorbeeld "2 melk" of "500 g kaas".',
  fetchingTitle: 'Ophalen…',
  fetchingBody: 'De lijst wordt opgehaald. Dit duurt meestal een paar seconden.',
  nothingFoundTitle: 'Nog niets gevonden',
  nothingFoundBody: 'Vraag de ander om de app te openen. Wat binnenkomt, verschijnt vanzelf.',
  checkedSection: 'Afgevinkt',
  clearChecked: 'Afgevinkte wissen',
  share: 'Delen',
  menu: 'Meer',
  rename: 'Hernoemen',
  deleteList: 'Lijst verwijderen',
  leaveList: 'Lijst verlaten',
  undo: 'Ongedaan maken',
  itemDeleted: (name: string) => `"${name}" verwijderd`,
  itemsCleared: (n: number) => (n === 1 ? '1 item gewist' : `${n} items gewist`),
  checkItem: (name: string) => `${name} afvinken`,
  uncheckItem: (name: string) => `${name} terugzetten`,
  editItem: (name: string) => `${name} bewerken`,
  suggestionLabel: (name: string) => `${name} toevoegen`,
  duplicateTitle: 'Staat al op de lijst',
  duplicateBody: (name: string) => `"${name}" staat al op je lijst.`,
  duplicateAddAnyway: 'Toch toevoegen',
  duplicateIncrease: 'Hoeveelheid verhogen',

  // Item bewerken
  editTitle: 'Bewerken',
  name: 'Naam',
  quantity: 'Hoeveelheid',
  unit: 'Eenheid',
  unitOther: 'Andere eenheid',
  note: 'Notitie',
  notePlaceholder: 'Bijvoorbeeld: het merk dat we altijd nemen',
  category: 'Categorie',
  deleteItem: 'Verwijderen',
  /** UX-15/UX-16: rode actie achter een rij na swipe naar links, en de accessibility action op de rij. */
  swipeDelete: 'Verwijderen',
  swipeDeleteItem: (name: string) => `${name} verwijderen`,
  swipeDeleteList: (name: string) => `Lijst ${name} verwijderen`,
  done: 'Klaar',

  // Delen
  shareTitle: 'Lijst delen',
  shareIntro: 'Laat de ander deze code scannen in BOODSCHAP! (Lijst toevoegen → Scannen), of stuur de tekst.',
  shareSend: 'Delen…',
  copyCode: 'Kopieer code',
  copied: 'Code gekopieerd',
  readyToJoin: 'Klaar om te koppelen',
  notYetReady: 'Bezig met klaarzetten… De ander kan straks koppelen.',
  shareCodeLabel: 'Code',
  shareMessageIntro: 'Doe mee met mijn boodschappenlijst in BOODSCHAP!',

  // Koppelen
  joinTitle: 'Lijst toevoegen',
  scanTab: 'Scannen',
  pasteTab: 'Code plakken',
  scanHint: 'Richt de camera op de QR-code op de telefoon van de ander.',
  cameraNeeded: 'BOODSCHAP! heeft de camera nodig om de code te scannen.',
  allowCamera: 'Camera toestaan',
  cameraDenied: 'De camera is niet toegestaan. Je kunt de code ook plakken.',
  usePaste: 'Code plakken',
  pastePlaceholder: 'Plak hier de tekst of code die je hebt gekregen',
  pasteFromClipboard: 'Plakken',
  join: 'Koppelen',
  joining: 'Bezig met koppelen…',
  alreadyPresent: 'Deze lijst staat al op je telefoon.',
  joinErrors: {
    'geen-code': 'Er staat geen BOODSCHAP!-code in deze tekst.',
    beschadigd: 'Deze code is beschadigd of onvolledig. Vraag de ander om de code opnieuw te sturen.',
    controlesom: 'Deze code klopt niet. Controleer of je hem helemaal goed hebt overgenomen.',
    'nieuwere-versie': 'Deze code is gemaakt met een nieuwere versie van de app. Werk de app bij.',
  } as Record<'geen-code' | 'beschadigd' | 'controlesom' | 'nieuwere-versie', string>,

  // Instellingen
  settingsTitle: 'Instellingen',
  relaysTitle: 'Relays',
  relaysIntro:
    'BOODSCHAP! synchroniseert via openbare Nostr-relays. Die bewaren alleen versleutelde berichten; ze kunnen je boodschappen niet lezen. Je hebt er minstens één nodig.',
  relayPlaceholder: 'wss://relay.voorbeeld.nl',
  addRelay: 'Relay toevoegen',
  relayInputLabel: 'Nieuw adres invoeren',
  removeRelay: (url: string) => `${url} verwijderen`,
  relayInvalid: 'Een relay-adres begint met wss:// en mag geen spaties bevatten.',
  relayMinimum: 'Je hebt minstens één relay nodig.',
  resetRelays: 'Standaardrelays herstellen',
  privacyTitle: 'Privacy',
  privacyBody:
    'Je lijsten staan op je telefoon. Bij een gedeelde lijst gaan wijzigingen end-to-end versleuteld via relays naar de telefoons waarmee je deelt. Een relay ziet alleen dat er versleutelde berichten zijn, hoe groot ze zijn en wanneer ze komen; niet wat erin staat. Er is geen account, geen server van BOODSCHAP! en geen tracking.',
  aboutTitle: 'Over',
  aboutBody: 'BOODSCHAP! is gratis, zonder advertenties, en open source.',
  // ST-07: verwijzingen
  privacyPolicy: 'Privacybeleid',
  support: 'Support en contact',
  openSourceLicenses: 'Open-source licenties',
  sourceCode: 'Broncode',
  opensInBrowser: 'opent in de browser',
  licensesTitle: 'Open-source licenties',
  licensesIntro: (n: number) => `BOODSCHAP! is gemaakt met ${n} open-sourcepakketten. Hieronder per pakket de licentie en de makers, en daarna de volledige licentieteksten.`,
  licenseTextsTitle: 'Licentieteksten',
  version: (v: string) => `Versie ${v}`,

  // Bevestigingen (UX-07, §12.1)
  confirm: {
    deleteLocalTitle: 'Lijst verwijderen?',
    deleteLocalBody: (name: string) => `‘${name}’ en alle items worden verwijderd. Dit kan niet ongedaan worden gemaakt.`,
    deleteSharedTitle: 'Gedeelde lijst verwijderen?',
    deleteSharedBody: (name: string) =>
      `‘${name}’ wordt ook verwijderd op alle telefoons waarmee je deze lijst deelt. Wil je hem alleen van deze telefoon halen? Kies dan ‘Lijst verlaten’.`,
    deleteButton: 'Verwijderen',
    deleteEverywhere: 'Overal verwijderen',
    leaveTitle: 'Lijst verlaten?',
    leaveBody: (name: string) =>
      `Deze telefoon synchroniseert ‘${name}’ niet meer. De anderen houden de lijst. Wie de code heeft, kan altijd weer meedoen.`,
    leaveKeep: 'Verlaten, kopie houden',
    leaveDelete: 'Verlaten en verwijderen',
    clearTitle: 'Afgevinkte items wissen?',
    clearBody: (n: number) => `${n} afgevinkte items wissen?`,
    clearButton: 'Wissen',
  },

  // Sync-status (UX-02)
  status: {
    lokaal: 'Alleen op dit toestel',
    gesynchroniseerd: 'Gesynchroniseerd',
    bezig: 'Synchroniseren…',
    ophalen: 'Ophalen…',
    offline: (n: number) => (n === 0 ? 'Offline' : n === 1 ? 'Offline — 1 wijziging wacht' : `Offline — ${n} wijzigingen wachten`),
    beperkt: (x: number, y: number) => `Beperkt verbonden (${x} van ${y})`,
    fout: 'Synchronisatiefout',
    foutSub: 'Je wijzigingen staan veilig op deze telefoon. De app blijft het opnieuw proberen.',
    nieuwereVersie: 'Werk de app bij om deze lijst te synchroniseren',
    teGroot: 'Lijst te groot om te synchroniseren',
  },

  // Fouten (AppErrorCode)
  errors: {
    'opslaan-mislukt': 'Opslaan is mislukt. Je laatste wijziging is teruggedraaid.',
    'lijst-verwijderd-door-ander': 'Een lijst is verwijderd door iemand met wie je hem deelde.',
  },
  inputErrors: {
    'naam-leeg': 'Vul een naam in.',
    'naam-te-lang': 'Die naam is te lang.',
    'notitie-te-lang': 'De notitie is te lang (maximaal 200 tekens).',
    'eenheid-te-lang': 'De eenheid is te lang.',
    'hoeveelheid-ongeldig': 'Vul een geldig getal in.',
    'categorie-ongeldig': 'Kies een categorie.',
  } as Record<string, string>,
  genericError: 'Dat lukte niet. Probeer het opnieuw.',

  units: ['stuks', 'g', 'kg', 'l', 'ml', 'pak', 'fles'],
  categories: {
    'groente-fruit': 'Groente & fruit',
    'brood-gebak': 'Brood & gebak',
    'vlees-vis': 'Vlees & vis',
    'vleeswaren-kaas': 'Vleeswaren & kaas',
    'zuivel-eieren': 'Zuivel & eieren',
    'ontbijt-beleg': 'Ontbijt & beleg',
    'pasta-rijst-wereld': 'Pasta, rijst & wereldkeuken',
    'houdbaar-conserven': 'Houdbaar & conserven',
    'snacks-snoep': 'Snacks & snoep',
    dranken: 'Dranken',
    diepvries: 'Diepvries',
    huishouden: 'Huishouden & schoonmaak',
    verzorging: 'Verzorging & drogisterij',
    'baby-kind': 'Baby & kind',
    huisdieren: 'Huisdieren',
    overig: 'Overig',
  } as Record<CategoryId, string>,
} as const;
