// Ingebouwd woordenboek (F-08): gangbare Nederlandse producten, samenstellingen en bekende supermarktmerken.
// Termen staan expliciet, gescheiden door komma's (meerwoordtermen mogen). Ze worden genormaliseerd met normalizeName;
// meervoud wordt via singularCandidates gevonden, samenstellingen via het hoofd (§8.1 stap 6).
// Bij dezelfde term in twee categorieën wint de eerste in de volgorde hieronder.
import type { CategoryId } from '../types';
import { normalizeName } from './normalize';

const RAW: [Exclude<CategoryId, 'overig'>, string][] = [
  // ---- specifieke termen die anders via het hoofd van een samenstelling verkeerd zouden vallen
  ['ontbijt-beleg', `pindakaas, notenpasta, chocoladepasta, speculaaspasta, smeerworst, chocoladehagelslag, chocoladevlokken`],
  ['zuivel-eieren', `chocolademelk, chocomel, fristi, karnemelk, koffiemelk, slagroom, kookroom, drinkyoghurt, yoghurtdrank`],
  ['pasta-rijst-wereld', `kokosmelk, sojasaus, pindasaus, satesaus, woksaus, currysaus, kroepoek, nasi, bami`],
  ['diepvries', `ijs, roomijs, waterijs, schepijs, vanille ijs, ijsje, ijsjes, ijstaart, ijsblokjes, vissticks, visstick, fishsticks, diepvriespizza, diepvriesgroente, diepvriesspinazie, diepvriesfruit, diepvriesmaaltijd, diepvriesfriet, diepvriesbrood, diepvriesgarnalen, magnum, cornetto, viennetta, calippo, ben jerrys, ola, iglo, mora, mccain, aviko, dr oetker, patat, friet, frites, kroket, kroketten, frikandel, frikandellen, bitterballen, loempia, loempias, kipnuggets, kipcorn, spinazie a la creme, kant en klaar maaltijd, ovenschotel`],

  ['groente-fruit', `appel, peer, banaan, sinaasappel, handsinaasappel, mandarijn, clementine, citroen, limoen, grapefruit, kiwi, mango, ananas, meloen, watermeloen, galiameloen, druif, aardbei, framboos, blauwe bes, bosbes, braam, kers, pruim, perzik, nectarine, abrikoos, vijg, dadel, granaatappel, passievrucht, lychee, rabarber, avocado, tomaat, cherrytomaat, trostomaat, snoeptomaat, komkommer, paprika, puntpaprika, courgette, aubergine, ui, rode ui, sjalot, knoflook, prei, wortel, winterpeen, bospeen, worteltjes, aardappel, aardappelen, krieltjes, zoete aardappel, broccoli, bloemkool, spruitje, spruitjes, boerenkool, spinazie, andijvie, sla, ijsbergsla, kropsla, rucola, veldsla, witlof, spitskool, rode kool, witte kool, savooiekool, chinese kool, paksoi, champignon, kastanjechampignon, paddenstoel, shiitake, oesterzwam, sperzieboon, snijboon, tuinboon, peultje, sugarsnap, doperwt, maiskolf, radijs, knolselderij, bleekselderij, selderij, venkel, pastinaak, koolrabi, biet, rode biet, asperge, artisjok, gember, verse kruiden, peterselie, basilicum, koriander, bieslook, dille, munt, rozemarijn, tijm, taugé, pompoen, flespompoen, lente ui, bosui, groente, fruit, slamix, soepgroente, rauwkost, wokgroente, fruitsalade, appelpartjes, mandarijntjes, kokosnoot, olijf, olijven`],
  ['brood-gebak', `brood, volkorenbrood, witbrood, bruinbrood, tarwebrood, meergranenbrood, roggebrood, speltbrood, desembrood, zuurdesembrood, stokbrood, baguette, ciabatta, focaccia, pistolet, bolletje, broodje, broodjes, kaiserbroodje, croissant, krentenbol, krentenbollen, krentenbrood, rozijnenbrood, suikerbrood, beschuit, knackebrod, cracker, crackers, toast, pita, pitabroodje, naan, taart, appeltaart, vlaai, gebak, ontbijtkoek, peperkoek, cake, tompouce, donut, muffin, brownie, kaneelbroodje, pizzadeeg, pannenkoek, pannenkoeken, poffertjes, tijgerbrood, maisbrood, bolletje, lieken, peijnenburg, roomboterkoek, gevulde koek, saucijzenbroodje`],
  ['vlees-vis', `vlees, gehakt, rundergehakt, half om half gehakt, kipgehakt, kipfilet, kippendij, kippendijen, kip, kippenpoot, kippenvleugel, drumstick, biefstuk, rundvlees, runderlap, sukadelap, stoofvlees, varkensvlees, varkenshaas, speklap, spekreepjes, ontbijtspek, karbonade, schnitzel, slavink, hamburger, burger, worst, braadworst, rookworst, saucijs, shoarma, gyros, kalkoen, lamsvlees, lamskotelet, spareribs, procureur, hachee, vis, zalm, zalmfilet, kabeljauw, tilapia, pangasius, koolvis, tonijnsteak, makreel, haring, garnaal, gamba, scampi, mossel, mosselen, kibbeling, lekkerbekje, forel, schol, tong, inktvis, kreeft, krab, gerookte makreel, vegetarische burger, vegaburger, tofu, tempeh, gehaktballen, kipschnitzel, cordon bleu, kipdrumsticks`],
  ['vleeswaren-kaas', `kaas, jonge kaas, belegen kaas, oude kaas, jong belegen kaas, geitenkaas, schapenkaas, brie, camembert, mozzarella, burrata, feta, parmezaan, parmezaanse kaas, pecorino, gorgonzola, emmentaler, gruyere, cheddar, manchego, geraspte kaas, kaasplakken, plakken kaas, roomkaas, smeerkaas, zuivelspread, huttenkase, cottage cheese, leerdammer, old amsterdam, beemster, milner, maaslander, parrano, president, galbani, boursin, philadelphia, ham, achterham, boterhamworst, cervelaat, salami, chorizo, filet americain, rosbief, beleg, vleeswaren, rookvlees, pastrami, leverworst, pate, gekookte ham, schouderham, fricandeau, kipfilet beleg, kalkoenfilet beleg, gerookte zalm, tapenade, hummus, humus, salade, eiersalade, kipsalade, zalmsalade, johma, herta, zwanenberg`],
  ['zuivel-eieren', `melk, halfvolle melk, volle melk, magere melk, lactosevrije melk, yoghurt, griekse yoghurt, turkse yoghurt, kwark, vla, pudding, toetje, room, zure room, creme fraiche, boter, roomboter, margarine, halvarine, bak en braad, ei, eieren, scharreleieren, vrije uitloop eieren, skyr, havermelk, sojamelk, amandelmelk, plantaardige melk, koffieroom, mascarpone, ricotta, campina, optimel, almhof, vifit, danone, activia, alpro, arla, mona, melkunie, lurpak, blue band, becel, kerrygold, oatly, danoontje, petit gervais`],
  ['ontbijt-beleg', `hagelslag, vlokken, jam, aardbeienjam, confituur, honing, appelstroop, stroop, muisjes, gestampte muisjes, speculoos, nutella, cornflakes, muesli, granola, cruesli, havermout, brinta, ontbijtgranen, pap, calve, de ruijter, venz, kelloggs, special k, quaker, chocopops, ontbijtdrank`],
  ['pasta-rijst-wereld', `pasta, spaghetti, macaroni, penne, fusilli, farfalle, tagliatelle, lasagne, lasagnebladen, ravioli, tortellini, gnocchi, noedel, noedels, noodles, mie, mienestjes, mihoen, ramen, udon, rijstnoedels, rijst, basmatirijst, zilvervliesrijst, risottorijst, sushirijst, jasmijnrijst, couscous, bulgur, quinoa, taco, tacos, tacoschelp, burrito, enchilada, nachos, ketjap, sambal, currypasta, wokolie, pastasaus, pesto, tomatensaus, spaghettisaus, lasagnesaus, nori, wasabi, sushi, falafel, conimex, go tan, koh thai, grand italia, old el paso, lassie, uncle bens, de cecco, barilla, miracoli`],
  ['houdbaar-conserven', `bloem, meel, zelfrijzend bakmeel, suiker, kristalsuiker, basterdsuiker, poedersuiker, zout, peper, olie, olijfolie, zonnebloemolie, frituurolie, azijn, balsamico, mayonaise, mayo, ketchup, mosterd, curry, saus, fritessaus, slasaus, dressing, bouillon, bouillonblokje, bouillonblokjes, jus, tomatenpuree, gepelde tomaten, passata, tomatenblokjes, blik tomaten, bonen, kidneybonen, bruine bonen, witte bonen, kikkererwten, linzen, mais, mais in blik, doperwten in blik, tonijn, tonijn in blik, sardines, ansjovis, knakworst, knakworstjes, soep, tomatensoep, erwtensoep, soep in blik, paneermeel, bakpoeder, gist, vanillesuiker, kruiden, specerijen, paprikapoeder, kaneel, nootmuskaat, oregano, gedroogde kruiden, kruidenmix, rozijnen, gedroogd fruit, noten, walnoot, amandel, amandelen, cashewnoot, hazelnoot, pinda, pindas, ongezouten noten, zaden, pitten, chiazaad, lijnzaad, pompoenpitten, zonnebloempitten, appelmoes, augurk, augurken, zilveruitjes, rode bieten in pot, kokosrasp, bakchocolade, chocolade om te bakken, puree, aardappelpuree, knorr, honig, unox, hak, bonduelle, remia, heinz, calve mayonaise, bertolli, zwan, smak, maizena, custard, pannenkoekmix, cakemix`],
  ['snacks-snoep', `chips, paprikachips, naturel chips, ribbelchips, nootjes, borrelnootjes, zoutjes, popcorn, koek, koekje, koekjes, biscuit, biscuitjes, stroopwafel, stroopwafels, speculaas, kletskop, bokkenpootjes, chocola, chocolade, chocoladereep, reep, snoep, drop, dropjes, winegum, winegums, spekjes, zuurtjes, kauwgom, snoepgoed, lolly, marsepein, wafel, wafels, pepernoten, kruidnoten, chocoladeletter, paaseitjes, krakelingen, mueslireep, proteinereep, nacho chips, tortilla chips, pretzels, kaaskoekjes, haribo, venco, katja, autodrop, red band, mentos, smarties, mms, mars, snickers, twix, bounty, kitkat, tonys chocolonely, milka, verkade, cote dor, droste, lays, doritos, pringles, croky, duyvis, lu, oreo, sultana, liga, tuc, bolletje zoutjes, napoleon, sportlife, toffees, chocoladerozijnen, borrelhapjes, studentenhaver`],
  ['dranken', `water, mineraalwater, spa, spa rood, spa blauw, chaudfontaine, bruiswater, koolzuurhoudend water, frisdrank, cola, cola zero, sinas, sinaasappelsap, appelsap, jus dorange, sap, smoothie, ranja, limonade, siroop, ijsthee, ice tea, energiedrank, tonic, bitter lemon, ginger ale, koffie, koffiebonen, gemalen koffie, koffiepads, koffiecups, cups, oploskoffie, thee, groene thee, kruidenthee, muntthee, bier, alcoholvrij bier, speciaalbier, wijn, rode wijn, witte wijn, rose, prosecco, champagne, cider, jenever, whisky, wodka, rum, gin, likeur, port, sherry, sportdrank, kokoswater, kombucha, coca cola, pepsi, fanta, sprite, seven up, lipton, heineken, grolsch, amstel, hertog jan, brand, bavaria, jupiler, la chouffe, affligem, douwe egberts, nescafe, senseo, pickwick, red bull, monster, appelsientje, roosvicee, taksi, karvan cevitam, wicky, capri sun, rivella, royal club, crystal clear, hero sap, dubbeldrank`],
  ['huishouden', `wc papier, toiletpapier, keukenpapier, keukenrol, tissues, zakdoekjes, afwasmiddel, vaatwastablet, vaatwastabletten, vaatwasmiddel, glansspoelmiddel, vaatwaszout, wasmiddel, waspoeder, wascapsules, wasverzachter, vlekkenverwijderaar, allesreiniger, schoonmaakmiddel, ontkalker, wc reiniger, wc blok, bleek, chloor, glasreiniger, spons, sponzen, schuurspons, vaatdoek, theedoek, vuilniszak, vuilniszakken, afvalzak, pedaalemmerzak, boterhamzakje, boterhamzakjes, diepvrieszak, diepvrieszakjes, aluminiumfolie, folie, vershoudfolie, bakpapier, lucifers, kaars, kaarsen, waxinelichtjes, batterij, batterijen, lamp, lampje, gloeilamp, ledlamp, huishoudhandschoenen, dweil, stofzuigerzak, luchtverfrisser, wasknijpers, ontstopper, schoonmaakdoekjes, dreft, sun, finish, robijn, ariel, persil, omo, witte reus, glorix, ajax, mr proper, cif, page, edet, zewa, lotus, albal, toppits, duracell, varta, calgon, vanish, wc eend, swiffer`],
  ['verzorging', `tandpasta, tandenborstel, tandenborstels, flosdraad, mondwater, shampoo, conditioner, douchegel, zeep, handzeep, deodorant, deo, bodylotion, creme, dagcreme, nachtcreme, zonnebrand, zonnebrandcreme, aftersun, scheermesjes, scheerschuim, maandverband, tampons, inlegkruisjes, wattenschijfjes, wattenstaafjes, nagellakremover, haarlak, haargel, gel, paracetamol, ibuprofen, pijnstillers, pleisters, vitamines, vitamine c, multivitamine, lenzenvloeistof, lippenbalsem, make up, mascara, oogdruppels, handcreme, keelpastilles, hoestdrank, neusspray, zendium, prodent, aquafresh, colgate, oral b, sensodyne, andrelon, dove, nivea, axe, rexona, head shoulders, elvive, gliss, sanex, palmolive, always, libresse, kotex, ob tampons, gillette, wilkinson, davitamon, dettol, vaseline`],
  ['baby-kind', `luiers, luier, billendoekjes, babydoekjes, babyvoeding, flesvoeding, zuigelingenvoeding, opvolgmelk, babypap, knijpfruit, fruithapje, groentehapje, speen, fopspeen, babyshampoo, zwemluiers, oefenbroekjes, babybiscuit, babyolie, babycreme, pampers, huggies, nutrilon, hero baby, olvarit, bambix, zwitsal, kruidvat luiers, babyfles`],
  ['huisdieren', `kattenvoer, hondenvoer, kattenbakvulling, kattenbakkorrels, brokken, hondenbrokken, kattenbrokken, natvoer, hondensnack, kattensnack, hondenkoekjes, kattensnoepjes, vogelvoer, visvoer, konijnenvoer, knaagdierenvoer, hooi, strooisel, kauwbot, poepzakjes, vlooienmiddel, kattenvoer blik, whiskas, felix, sheba, gourmet, pedigree, frolic, kitekat, hills, royal canin, catsan, purina, brekkies, friskies, perfect fit, cesar, dreamies, schmackos`],
];


// ---- Uitbreiding (D-ET-07): gangbare producten van AH en Jumbo, breed per categorie. Volgorde = voorrang.
const EXTRA: [Exclude<CategoryId, 'overig'>, string][] = [
  // Specifiek vóór algemeen: termen die anders via een kop of voorvoegsel verkeerd vallen.
  ['snacks-snoep', `tortillachips, zoute pindas, zoute pinda's, gezouten pinda's, zoute nootjes, pepermunt, pepermuntjes, kattentong, kattentongen, borrelnoten, borrelnoot, nootjesmix, notenmix, studentenhaver, chocoladepinda's, zure matten, salmiak, zoute drop, muntdrop, toverballen, schuimpjes, spekkies, dropveters, lolly's, chocoladereep, chocoladerepen, bonbons, truffels, pralines, chocolade eitjes, paaseieren, kerstkransjes, chocoladekransjes, marshmallows, popcorn zoet, tortillachips, maischips, groentechips, kroepoekchips, cashewnoten gezouten, pinda's gezouten, japanse mix, rijstcrackers, mergpijpjes, kokosmakronen, bitterkoekjes, amandelkoekjes, speculaasjes, roomboterkoekjes, spritsen, zandkoekjes, chocoladekoekjes, havermoutkoekjes, biscuits, liga, sultana, evergreen, fruitbiscuit, prince, bastogne, café noir, mars, milky way, maltesers, m&m's, kinder bueno, kinder surprise, kinder chocolade, kinderchocolade, toblerone, ritter sport, lindt, verkade reep, droste pastilles, fruittella, mentos, tic tac, autodrop, venco drop, katja, red band, haribo goudbeertjes, oreo, pringles, lay's, doritos, cheetos, wokkels, chipito, hamka's, nibb-it, smiths, paprika chips`],
  ['brood-gebak', `bol, bolletje, zuurdesem, desembrood, zuurdesembrood, zuurdesembol, waldkorn, waldkornbrood, bollen, bolletjes, boterkoek, roomboterkoek, gevulde koek, appelflap, appelflappen, bagel, bagels, croissantjes, chocoladebroodje, chocoladebroodjes, saucijzenbroodje, worstenbroodje, kaasbroodje, kaasbroodjes, pistolets, afbakbroodjes, afbakbrood, stokbroodjes, kaiserbroodjes, harde broodjes, zachte broodjes, bruine bollen, witte bollen, hamburgerbroodjes, hotdogbroodjes, tijgerbol, tijgerbrood, waldkornbrood, maisbrood, rozijnenbollen, krentenbollen, suikerbollen, beschuitbollen, krentenwegge, suikerbrood, vruchtencake, marmercake, citroencake, ontbijtkoek, peperkoek, eierkoek, eierkoeken, krakeling, appelcarre, kersenvlaai, rijstevlaai, kwarktaart, slagroomtaart, tompoes, moorkop, soesjes, bossche bol, oliebollen, appelbeignets, croissants, pain au chocolat, rijstwafels, rijstwafel, crackers, cracottes, matzes, knackebrod, wasa, toastjes, toast, beschuit, beschuiten, paneermeel brood, broodje, broodjes, lunchbroodjes, wraps volkoren, naanbrood, pitabroodjes, turks brood, focaccia, ciabatta, desem, spelt brood`],
  ['ontbijt-beleg', `vruchtenhagel, anijshagel, hagel, chocoladehagel, melkchocoladehagel, pure hagelslag, gestampte muisjes, roze muisjes, blauwe muisjes, chocoladepasta, hazelnootpasta, speculoospasta, pindakaas crunchy, notenpasta, amandelpasta, chocopasta, kokosbrood, ontbijtkoek beleg, appelstroop, perenstroop, schenkstroop, honing vloeibaar, jam aardbei, frambozenjam, kersenjam, sinaasappelmarmelade, marmelade, abrikozenjam, bosvruchtenjam, vruchtenspread, chocoladevlokken, vlokken melk, vlokken puur, hagelslag puur, smeerkaas beleg, cornflakes, krokante muesli, havermoutpap, brinta, cruesli, granola, special k, kelloggs, quaker havermout, griesmeel, pap, ontbijtgranen, muesli, linzenkoekjes`],
  ['diepvries', `diepvries, diepvriesgroente, diepvriesfruit, diepvriesframbozen, diepvriesaardbeien, diepvriesbessen, roerbakgroente diepvries, spinazie diepvries, doperwten diepvries, sperziebonen diepvries, bladerdeeg, bladerdeegplakjes, pizzabodem diepvries, ijsjes, waterijsjes, roomijs vanille, vanilleijs, chocolade ijs, sorbet, ijstaart, frietjes, friet, frieten, aardappelkroketten, rösti, rosti, aardappelschijfjes, kipnuggets, kipburgers diepvries, vissticks, kibbeling diepvries, garnalen diepvries, pangasiusfilet diepvries, loempia's, mini loempia's, bitterballen, kaassoufflés, kaassouffle, frikandellen, kroketten, snacks diepvries, pizza diepvries, maaltijd diepvries, nasi diepvries, lasagne diepvries, smoothiefruit, ijsblokjes`],
  ['huisdieren', `hondenkluif, kluif, kluiven, hondenkoekjes, hondensnacks, hondenbrokjes, hondenvoer blik, hondenvoer droog, kattenbrokjes, kattenvoer droog, kattenvoer nat, kattensnacks, kattengras, kattenbak, kattenbakvulling, kattenbakkorrels, krabpaal, vogelzaad, vogelvoer, strooivoer, vetbollen, pindasnoeren, visvoer, konijnenkorrels, cavia voer, hooi, knaagdierenvoer, kauwstaaf, kauwstaven, dentastix, schmackos, felix, sheba, whiskas, gourmet gold, perfect fit, pedigree, frolic, cesar, royal canin, hills, purina, friskies, kitekat, catsan, applaws, vlooiendruppels, ontwormingsmiddel, poepzakjes, hondenshampoo`],
  ['baby-kind', `babyvoeding, babyhapjes, fruithapjes, groentehapjes, knijpzakjes, babykoekjes, babybiscuits, zuigelingenmelk, opvolgmelk, groeimelk, peutermelk, nutrilon, olvarit, bambix, hipp, ella's kitchen, babydoekjes, billendoekjes, luiers, pampers, huggies, broekjesluiers, zwemluiers, slabbetjes, flesspeen, fopspeen, tandjesgel, babyzeep, babyolie, babylotion, babycreme, zinkzalf, sudocrem`],
  ['zuivel-eieren', `eieren, ei, scharreleieren, biologische eieren, vrije uitloop eieren, verse melk, halfvolle melk, volle melk, magere melk, karnemelk, chocomel, fristi, yoghurt naturel, volle yoghurt, magere yoghurt, griekse yoghurt, skyr, kwark, magere kwark, volle kwark, vanillevla, chocoladevla, vla, pudding, griesmeelpudding, rijstepap, slagroom, kookroom, creme fraiche, zure room, roomboter, ongezouten boter, margarine, halvarine, blue band, becel, bak en braad boter, mascarpone, ricotta, kwark met fruit, danoontje, petit filou, yogho yogho, drinkyoghurt, optimel, vifit, actimel, yakult, alpro, havermelk, sojamelk, amandelmelk, rijstmelk, koffiemelk, slagroom spuitbus, toetjes, bulgaarse yoghurt, kefir, babybel, mini babybel`],
  ['vleeswaren-kaas', `kaas plakken, jonge kaas plakken, belegen kaas plakken, oude kaas plakken, kaasblokjes, geraspte kaas, parmezaan, mozzarella, burrata, feta, geitenkaas, brie, camembert, roquefort, gorgonzola, emmentaler, gouda, edammer, leerdammer, maaslander, beemster, old amsterdam, milner, la vache qui rit, kiri, philadelphia, boursin, smeerkaas, kaasspread, ham, achterham, beenham, gerookte ham, gekookte ham, parmaham, serranoham, prosciutto, salami, chorizo, cervelaat, boterhamworst, leverworst, smeerleverworst, leverpastei, pate, rosbief, fricandeau, kipfilet beleg, kalkoenfilet beleg, rookvlees, pastrami, gebraden gehakt, ontbijtspek beleg, filet americain, tartaar beleg, hummus, tapenade, pesto beleg, eiersalade, tonijnsalade, kipkerriesalade, krabsalade, huzarensalade, johma, olvarit kaas`],
  ['vlees-vis', `kipfilet, kippenfilet, kippendijfilet, kippenpoten, kippenvleugels, hele kip, kipdrumsticks, kipschnitzel, kipgehakt, kipreepjes, shoarmavlees, gyrosvlees, kalkoenfilet, kalkoenreepjes, rundergehakt, varkensgehakt, half om half, gehaktballen, hamburgers, slavinken, saucijzen, braadworst, rookworst, unox rookworst, verse worst, biefstuk, entrecote, ribeye, runderlappen, stoofvlees, sukadelappen, rosbief rauw, varkenshaas, varkensfilet, karbonades, speklappen, spekblokjes, ontbijtspek, spareribs, procureurlapjes, lamsrack, lamskoteletten, kalfsvlees, wild, konijn, vegetarische burger, vegaburger, vegetarisch gehakt, vegetarische kipstukjes, de vegetarische slager, garnalen, gamba's, zalm, zalmfilet, gerookte zalm stukjes, kabeljauw, kabeljauwfilet, koolvis, pangasius, tilapia, schol, tong, makreel, haring, maatjes, mosselen, kibbeling, lekkerbekjes, tonijnsteak, forel, sardientjes, inktvisringen, surimi, tofu, tempeh, seitan`],
  ['groente-fruit', `appels, peren, bananen, sinaasappels, mandarijnen, clementines, citroenen, limoenen, kiwi's, mango's, ananas, meloen, watermeloen, druiven, pitloze druiven, aardbeien, frambozen, blauwe bessen, bramen, kersen, pruimen, perziken, nectarines, abrikozen, vijgen, dadels, granaatappel, passievrucht, avocado's, tomaten, cherrytomaten, snoeptomaatjes, komkommer, paprika's, puntpaprika, courgette, aubergine, uien, rode uien, sjalotten, knoflook, prei, wortelen, winterpeen, bospeen, aardappelen, krieltjes, zoete aardappelen, broccoli, bloemkool, spruitjes, boerenkool, spinazie, andijvie, sla, ijsbergsla, rucola, veldsla, witlof, spitskool, rode kool, witte kool, paksoi, champignons, kastanjechampignons, sperziebonen, snijbonen, peultjes, sugarsnaps, radijs, knolselderij, bleekselderij, venkel, pastinaak, rode bieten, asperges, gember, verse munt, verse basilicum, verse peterselie, verse koriander, bosuitjes, lente-ui, taugé, pompoen, mais kolf, maiskolven, fruitbakje, gesneden groente, groentemix, roerbakgroente, soepgroente, rauwkostsalade, slamelange, maaltijdsalade, salademix, vers fruit, fruitsalade, appeltjes, peertjes, mandarijntjes`],
  ['dranken', `spa rood, spa blauw, bronwater, mineraalwater, koolzuurhoudend water, cola, cola zero, pepsi max, fanta, sprite, 7up, ice tea, lipton ice tea, fuze tea, appelsap, sinaasappelsap, jus d'orange, multivitaminesap, tomatensap, druivensap, cranberrysap, smoothie, ranja, limonadesiroop, karvan cevitam, roosvicee, dubbelfrisss, taksi, capri-sun, chocomel blik, energiedrank, red bull, monster energy, sportdrank, aa drink, isostar, koffie, koffiebonen, filterkoffie, snelfiltermaling, koffiecups, nespresso cups, dolce gusto, senseo pads, oploskoffie, cappuccino poeder, thee, zwarte thee, groene thee, rooibos, muntthee, kamillethee, pickwick, lipton thee, bier, pils, speciaalbier, alcoholvrij bier, radler, witbier, ipa, heineken, amstel, grolsch, bavaria, hertog jan, jupiler, brand, wijn, rode wijn, witte wijn, rosé, mousserende wijn, prosecco, cava, champagne, port, sherry, jenever, whisky, rum, wodka, gin, likeur, advocaat, baileys, cider, tonic, bitter lemon, ginger ale, ginger beer, kombucha, kokoswater, havermelk barista`],
  ['houdbaar-conserven', `bloem, tarwebloem, zelfrijzend bakmeel, maizena, suiker, kristalsuiker, basterdsuiker, poedersuiker, rietsuiker, vanillesuiker, bakpoeder, gist, cacao, cacaopoeder, chocoladedruppels, bakchocolade, hagelslag bakken, rozijnen, krenten, gedroogde abrikozen, gedroogde vruchten, noten, walnoten, hazelnoten, amandelen, cashewnoten, pecannoten, pistachenoten, pinda's, pinda's ongezouten, zonnebloempitten, pompoenpitten, sesamzaad, lijnzaad, chiazaad, olijfolie, zonnebloemolie, arachideolie, frituurolie, frituurvet, azijn, balsamicoazijn, mayonaise, ketchup, curry ketchup, mosterd, fritessaus, joppiesaus, knoflooksaus, sambal saus, satésaus, pindasaus, barbecuesaus, slasaus, dressing, vinaigrette, bouillon, bouillonblokjes, kippenbouillon, groentebouillon, jus, mix voor, kruidenmix, kruiden, specerijen, zout, peper, paprikapoeder, kerriepoeder, komijn, kaneel, nootmuskaat, oregano, gedroogde basilicum, laurier, knoflookpoeder, tomatenpuree, passata, gepelde tomaten, tomatenblokjes, kidneybonen, bruine bonen, witte bonen, kikkererwten, linzen, mais, doperwten en wortelen, sperziebonen in pot, champignons in blik, ananas op sap, perziken op sap, fruitcocktail, appelmoes, augurken, zilveruitjes, rode kool in pot, zuurkool, olijven in pot, kappertjes, tonijn in olie, tonijn in water, zalm in blik, sardines, makreel in tomatensaus, knakworstjes, unox knakworst, soep in blik, soep in zak, cup a soup, erwtensoep, tomatensoep, groentesoep, kippensoep, noedelsoep, pannenkoekenmix, poffertjesmix, cakemix, brownie mix, pizzamix, puree poeder, aardappelpuree, croutons, paneermeel, knorr, honig, conimex mix, maggi, ketjap manis`],
  ['pasta-rijst-wereld', `spaghetti, macaroni, penne, fusilli, farfalle, tagliatelle, linguine, lasagnebladen, ravioli, tortellini, gnocchi, verse pasta, volkoren pasta, mie, mienestjes, noedels, eiernoedels, rijstnoedels, udon, ramen noedels, wokmie, mihoen, rijst, witte rijst, basmati rijst, zilvervliesrijst, pandanrijst, jasmijnrijst, risottorijst, paella rijst, sushi rijst, couscous, bulgur, quinoa, tortilla's, tortillas, tortilla, wraps, wrap, tortilla wraps, taco's, tacoschelpen, nachochips, salsa, guacamole, burrito kit, fajita kit, wraps mexicaans, kokosmelk, kokosroom, currypasta, rode currypasta, groene currypasta, tikka masala saus, sojasaus, ketjap, oestersaus, sweet chili saus, sriracha, wasabi, gember ingelegd, nori vellen, sushi kit, kroepoek, kroepoek garnalen, atjar, bumbu, nasi bumbu, bami bumbu, sate, falafel, pita, hummus wereld, pastasaus, tomatensaus, pesto, arrabbiata, carbonara saus, bolognese saus, lasagnesaus, grand italia, bertolli saus, conimex, go-tan, koh thai, old el paso, uncle ben's, lassie, de cecco, barilla, honig pasta, knorr wereldgerecht, maaltijdpakket`],
  ['huishouden', `toiletpapier, wc-papier, keukenrol, keukenpapier, tissues, zakdoekjes, servetten, afwasmiddel, vaatwastabletten, vaatwasmiddel, glansspoeler, vaatwaszout, wasmiddel, vloeibaar wasmiddel, waspoeder, wascapsules, wasverzachter, wasparfum, vlekverwijderaar, bleekmiddel, allesreiniger, badkamerreiniger, keukenreiniger, ontvetter, glasreiniger, wc-reiniger, toiletblokjes, ontkalker, schuurmiddel, schoonmaakazijn, groene zeep, sponsjes, schuursponsjes, microvezeldoek, vaatdoekjes, theedoeken, vuilniszakken, pedaalemmerzakken, afvalzakken, gft-zakken, boterhamzakjes, diepvrieszakjes, vershoudfolie, aluminiumfolie, bakpapier, muffinvormpjes, lucifers, aansteker, kaarsen, theelichtjes, waxinelichtjes, batterijen, lampen, ledlampen, huishoudhandschoenen, wasknijpers, luchtverfrisser, geurstokjes, insectenspray, muggenspray, ontstopper, dweil, stofdoek, stofzuigerzakken, prullenbakzakken, dreft, sun, finish, ariel, persil, omo, robijn, witte reus, biotex, vanish, glorix, ajax, cif, mr. proper, harpic, wc-eend, page, edet, zewa, kleenex, albal, toppits, calgon, swiffer, vileda, duracell, varta, philips lamp`],
  ['verzorging', `tandpasta, tandenborstel, elektrische tandenborstel opzetborstels, flosdraad, tandenstokers, mondwater, shampoo, conditioner, haarmasker, douchegel, badschuim, zeep, handzeep, deodorant, deoroller, bodylotion, handcrème, gezichtscrème, dagcrème, nachtcrème, reinigingsmelk, micellair water, wattenschijfjes, wattenstaafjes, scheermesjes, scheerschuim, scheergel, aftershave, ontharingscrème, maandverband, inlegkruisjes, tampons, menstruatiecup, zonnebrandcrème, aftersun, lippenbalsem, nagellak, nagellakremover, mascara, make-up remover, haarspray, haargel, haarwax, droogshampoo, haarverf, condooms, glijmiddel, pleisters, wondspray, paracetamol, ibuprofen, aspirine, keelpastilles, hoestsiroop, neusspray, zoutoplossing, vitamines, multivitaminen, vitamine d, magnesium, visolie capsules, oogdruppels, lenzenvloeistof, maagtabletten, rennie, ors, muggenzalf, voetcrème, eelt, zendium, prodent, aquafresh, colgate, sensodyne, oral-b, andrelon, dove, nivea, axe, rexona, sanex, palmolive, head & shoulders, elvive, garnier, l'oréal, always, libresse, gillette, wilkinson, davitamon, kruidvat, etos`],
];

for (const e of EXTRA) RAW.push(e);


// ---- Uitbreiding 2 (D-ET-07, ronde 3): koppen van samenstellingen en dunne categorieën.
const EXTRA2: [Exclude<CategoryId, 'overig'>, string][] = [
  ['dranken', `espresso, espressobonen, ristretto, lungo, cappuccino, latte macchiato, ijskoffie, koffiepads, koffiecapsules, decafe, cafeïnevrij`],
  // Koppen: maken samenstellingen herkenbaar zonder elk product apart te noemen.
  ['vlees-vis', `lappen, lapjes, hamlappen, hamlapjes, schouderlappen, schouderkarbonade, filet, filets, schnitzel, schnitzels, rollade, rollades, braadstuk, stoofstuk, stooflappen, poulet, kippoten, kipdij, kipdijen, kippendijen, drumsticks, vleugels, spiesjes, satespiesjes, kipspiesjes, gehaktbal, burger, burgers, kipburger, braadworstjes, chipolata, mergpijp, hamschijf, hamschijven, varkensribben, ribben, riblappen, runderriblappen, kogelbiefstuk, tartaar, tartaartjes, ossenhaas, kalfsoester, lamsgehakt, lamsbout, eendenborst, kalkoendij, wildzwijn, hertenbiefstuk, kipkerrie vlees, vegetarische schnitzel, vegaschnitzel, vegetarische balletjes, vegaballetjes, beyond burger, vivera, garde, valess, quorn, zalmmoten, moten, visfilet, vis, witvis, heek, zeebaars, dorade, tarbot, zeeduivel, scampi, kreeft, rivierkreeftjes, sint jakobsschelpen, oesters, ansjovis, paling, gerookte paling, gerookte makreel, bokking, sushi zalm`],
  ['huishouden', `doek, doeken, doekjes, verfrisser, verfrissers, bleekwater, chloor, chloorbleek, middel, reiniger, reinigers, ontkalkingsmiddel, ontsmettingsmiddel, desinfectiemiddel, desinfecterende doekjes, schoonmaakdoekjes, vochtige schoonmaakdoekjes, vloerreiniger, parketreiniger, ovenreiniger, wc-blokjes, toiletreiniger, toiletverfrisser, gootsteenontstopper, ontstoppingsmiddel, afvoerreiniger, kalkreiniger, roestvrijstaalreiniger, meubelpoets, zilverpoets, schoensmeer, schoenpoets, wasstrips, wasdoekjes, kleurvangers, wasnet, stijfsel, strijkwater, ontharder, natriumcarbonaat, soda, biotex wasmiddel, zeeppoeder, kristalsoda, spiritus, terpentine, lampenolie, kaarsjes, lucifersdoosjes, vuilniszak, zakken, afvalbakzakken, pedaalemmer zakken, sandwichzakjes, vriezakjes, vrieszakjes, sluitclips, elastiekjes, plakband, tape, schrijfpapier, printpapier, enveloppen, pennen, potloden, keukenhanddoek, handdoek, pannenspons, afwasborstel, afwasborstels, borstel, bezem, stoffer en blik, emmer, wasmand, wasknijper, wasrek, ventilator, verlengsnoer, stekkerdoos, zekering, zekeringen, lamp, gloeilamp, gloeilampen, spaarlamp, led lamp, batterij, knoopcel, oplaadbare batterijen, muizenval, mierenlokdoos, mottenballen, vliegenstrip, ontvochtiger, vochtvreter, open haard aanmaakblokjes, aanmaakblokjes, houtskool, bbq briketten, grillaansteker`],
  ['pasta-rijst-wereld', `rijstepapier, rijstpapier, rijstvellen, loempiavellen, wontonvellen, dimsum, dim sum, gyoza, bapao, loempia vers, springrolls, nasi goreng, bami goreng, mie goreng, nasi, bami, sambal oelek, sambal badjak, sambal manis, trassi, ketjap asin, sereh, citroengras, laos, djahe, koenjit, ketoembar, djinten, kerriesaus, boemboe, boemboe nasi, boemboe bami, boemboe rendang, rendang, sate kruiden, pindasaus mix, atjar tjampoer, seroendeng, emping, gebakken uitjes, gefrituurde uitjes, kroepoek emping, sushi gember, sushi azijn, rijstazijn, mirin, sake kookwijn, miso, misopasta, dashi, tahin, tahini, harissa, ras el hanout, za'atar, sumak, garam masala, tandoori kruiden, korma saus, butter chicken saus, madras curry, naan, chapati, roti, roti kruiden, papadums, poppadums, mango chutney, chutney, lime pickle, taco kruiden, fajita kruiden, burrito kruiden, enchilada saus, refried beans, jalapenos, jalapeño, chipotle, tortilla, tortillachips naturel, nacho kaas saus, salsa dip, chili con carne mix, couscous kruiden, falafelmix, bulgur salade, pad thai, pad thai saus, thaise currypasta, tom yum, tom kha, vissaus, fish sauce, hoisin, hoisinsaus, black bean saus, teriyakisaus, teriyaki saus, yakitori saus, ketjap manis saus, sushi azijn, panko, tempura meel, glasnoedels, soba, soba noedels, rijstnoedels breed, pho noedels, instant noedels, cup noodles, koreaanse noedels, gochujang, kimchi, sriracha mayo, wereldkeuken, tapas, paella, risotto, risottomix, orzo, gnocchi vers, cannelloni, conchiglie, rigatoni, pappardelle, orecchiette, tortiglioni, vermicelli, spaghettini, capellini, pastaschelpen, ditalini, mie nestjes, polenta, maismeel, griekse rijst`],
  ['zuivel-eieren', `boter, gezouten boter, ongezouten boter, roomboter ongezouten, grasboter, kruidenboter, knoflookboter, ghee, kwarkje, kwarkjes, yoghurtje, yoghurtjes, vruchtenyoghurt, aardbeienyoghurt, perzikyoghurt, kokosyoghurt, sojayoghurt, plantaardige yoghurt, haveryoghurt, griekse stijl yoghurt, magere vla, chocoladepudding, vanillepudding, karamelpudding, rijstpudding, mousse, chocolademousse, tiramisu, panna cotta, crème brûlée, room, crème, kookroom light, sojaroom, haverroom, plantaardige room, kwarktaartje, boerenyoghurt, hangop, lassi, ayran, karnemelk biologisch, lactosevrije melk, lactosevrije yoghurt, a2 melk, geitenmelk, koffieroom, koffiecreamer, cupjes koffiemelk, slagroomsoesjes, kipeieren, eitjes, eieren groot, eieren m, kwarteleitjes, eiwit, vloeibaar eiwit, gekookte eieren, eiersalade los, campina, arla, zuivelhoeve, optimel drink, almhof, mona, melkunie, friesche vlag, chocomel light, dubbelfrisss melk, vla vanille, dikke vla, boerenvla, griesmeelpap, karnemelkpap, roomyoghurt, monchou, roomkaas`],
  ['vleeswaren-kaas', `cervelaatworst, snijworst, plakjesworst, rookvlees plakjes, gegrilde kipfilet, kipfilet gerookt, kalkoenham, kipham, achterham plakjes, schouderham, katenspek, bacon, ontbijtspek plakjes, gerookt spek, zwitserse kaas, gruyère, gruyere, comté, manchego, pecorino, grana padano, cheddar, red leicester, stilton, blauwe kaas, schapenkaas, komijnekaas, kruidenkaas, nagelkaas, boerenkaas, belegen kaas, extra belegen kaas, jong belegen kaas, overjarige kaas, kaasplakken, plakken kaas, kaasschijfjes, geraspte mozzarella, pizzakaas, gourmetkaas, fonduekaas, raclettekaas, halloumi, paneer, cottage cheese, hüttenkäse, huttenkase, verse geitenkaas, roomkaas met kruiden, salade, salades, tonijnsalade los, zalmsalade, komkommersalade, selderijsalade, scharrelei salade, leverpastei plakken, paté, rillette, worstjes, droge worst, fuet, salametti, knakworst, frankfurter, bockworst, worstenbrood beleg, vegetarische plakjes, vega plakjes, vegetarische kipfilet plakjes, beleg, broodbeleg, tapenade groen, hummus naturel, rode pesto, groene pesto`],
  ['ontbijt-beleg', `hagelslag, chocoladehagelslag, vlokken, chocoladevlokken, fruit hagel, anijsblokjes, kokosbrood plakken, ontbijtkoek plakken, gember beleg, gemberbolus, honing creme, crèmehoning, pindakaas met stukjes nootjes, cashewnotenpasta, hazelnootpasta puur, nutella, calvé, calve pindakaas, de ruijter, venz, duyvis pindakaas, hero jam, jam, confiture, extra jam, halva, appelstroop rinse, lemon curd, kokosrasp beleg, chocoladepasta puur, speculoos, speculoospasta, biscoff, lotus pasta, notenmix ontbijt, ontbijtgranen chocolade, chocolade cruesli, krokante granola, havermout naturel, havervlokken, speltvlokken, tarwevlokken, rijstvlokken, gierst, ontbijtrepen, muesli repen, mueslirepen, ontbijtkoekjes, belvita, liga ontbijt, wafels ontbijt, crackers ontbijt, ontbijtshake, overnight oats, chiapudding, pindakaasspread, appelmoes beleg, smeerworst, smeerpaté, zoet beleg, hartig beleg`],
  ['diepvries', `diepvriesmaaltijd, diepvriespizza, diepvriesgroenten, diepvriesvis, diepvriesbroodjes, afbakbroodjes diepvries, ijs, ijsje, ijsco, raket, magnum, cornetto, ben & jerry's, ben en jerrys, hertog ijs, ola, ijsstokjes, softijs, frozen yoghurt, sorbetijs, schepijs, ijsbekers, bevroren fruit, bevroren bessen, bevroren mango, smoothiemix, spinazie a la creme, rodekool diepvries, wokgroenten diepvries, sperzieboontjes diepvries, doperwtjes diepvries, mais diepvries, broccoli diepvries, bloemkoolrijst, groenterijst, bladspinazie, gesneden spinazie, kruidenmix diepvries, ijsklontjes, vriesverse kruiden, diepvries kruiden, krieltjes diepvries, aardappelpartjes, wedges, frites, steakhouse friet, zoete aardappelfriet, kroketjes, bamischijven, nasischijven, kipcorn, frikandel, frikandelbroodjes, saucijzenbroodjes diepvries, mexicano, berenklauw, kaassticks, kipvingers, kip nuggets, chicken nuggets, garnalenkroket, viskroket, vispakket, zalmfilet diepvries, kabeljauw diepvries, pangasius, visburgers, gepaneerde vis, kibbeling vers, mosselen diepvries, scampi diepvries, gyoza diepvries, dumplings, pizza, pizza margherita, dr. oetker pizza, ristorante pizza, wagner pizza, lasagne, macaroni diepvries, ovenschotel diepvries, quiche, bladerdeeg plakjes, filodeeg, pizzadeeg diepvries, taartdeeg, kruimeldeeg, roomijs aardbei, ijstaart vanille, ijswafels, slagroomtaart diepvries, appeltaart diepvries, profiteroles, sorbet citroen`],
  ['snacks-snoep', `zure matjes, zure mat, stengels, zoutstengels, kaasstengels, zoute stengels, soepstengels, pretzels, pretzel, krakelingen zout, zoute krakelingen, zoutjes mix, borrelmix, crackers borrel, toastjes borrel, tuc, ritz, bugles, cheese balls, kaasballetjes, chipsjes, paprikachips naturel, ribbelchips paprika, chips zout, zoute chips, heksenkaas chips, cassavechips, linzenchips, popcornmais, magnetronpopcorn, zoete popcorn, zoute popcorn, notenmelange, gemengde noten, gezouten noten, gebrande pinda's, honingpinda's, wasabinoten, cocktailnoten, coatednoten, pistachenoten gezouten, macadamianoten, chocolade, pure chocolade, witte chocolade, chocoladeletter, chocoladeletters, chocoladereep puur, repen, reep, snoep, snoepjes, zuurtjes, kauwgom, kauwgum, dropjes, drop, laurierdrop, salmiakdrop, engelse drop, winegums, wine gums, gummies, gombeertjes, zure snoepjes, spekjes, marshmallow, lolly, toffees, toffee, karamels, fudge, nougat, praline, bonbon, paasei, chocoladekogels, pepernoten, kruidnoten, schuimpjes sint, borstplaat, marsepein, marsepeinen, suikerspin, ijswafeltjes, waffles, stroopwafels, mini stroopwafels, koekjes mix, sprits, kokoskoekjes, gevulde koeken, mergpijpjes, zebra's, kano's, koffiekoekjes, choco chip cookies, cookies, oreos, rijstwafels chocolade, mueslireep, proteïnereep, eiwitreep, energiereep, granolareep, notenreep`],
  ['baby-kind', `babyvoeding potje, fruitpotje, groentepotje, babypotje, babypotjes, baby pap, babypap, rijstebloem, babymelk, flesvoeding, kunstvoeding, startmelk, hypoallergene melk, hero baby, nutricia, kruidvat baby, baby rijstwafels, peuterkoekjes, peuterhapjes, babysnacks, knijpfruit, babycrackers, maiskrullen baby, babyfles, zuigfles, spenen, speen, bijtring, slab, slabbetje, babyshampoo, babybadje, badschuim baby, babywashgel, kinderzonnebrand, kindertandpasta, kindertandenborstel, luierzakjes, luieremmer zakken, luierbroekjes, nachtluiers, wegwerpluiers, verschoonmatjes, onderleggers, kraamverband, borstvoedingskompressen, zoogcompressen, tepelzalf, kinderparacetamol, zetpillen kind, neusspray kind, kinderpleisters, kindervitaminen, vitamine d baby, vitamine k druppels, kinderdrank, kinderyoghurt, knijpyoghurt, kinderkoekjes, traktatie, traktaties, uitdeelcadeautjes, kleurboek, krijtjes, stiften`],
  ['huisdieren', `brokken, brokjes, hondenbrokken, kattenbrokken, natvoer, droogvoer, blikvoer hond, blikvoer kat, maaltijdzakjes kat, kattenzakjes, kattenpaté, hondenworst, hondenbot, kauwbot, kauwbotten, dierensnacks, kattensnoepjes, kattenmelk, catnip, kattenkruid, kattenspeeltje, hondenspeeltje, hondenriem, halsband, hondenmand, kattenmand, kattenbakzakken, kattenbakgrit, kattengrit, zaagsel, strooisel, hooi knaagdier, knaagdierkorrels, cavia korrels, konijnenvoer, vogelzaadmix, parkietenzaad, kanarievoer, tuinvogelvoer, mezenbollen, meelwormen, vissenvoer, visvlokken, aquariumvoer, schildpadvoer, kippenvoer, kippengraan, paardenbrokken, vlooienband, tekenband, tekentang, ontworming, wormkuur, dierenshampoo, poepzakjes hond, hondenpoepzakjes, edgard & cooper, edgard cooper, yarrah, beaphar, trixie, vitakraft, versele-laga, sheba fine flakes, felix pouches, whiskas zakjes, pedigree dentastix, gimcat, brit care`],
  ['verzorging', `zonnebrand, zonnebrandspray, zonnemelk, zonnecrème, lotion, zalf, crème gezicht, gezichtsmasker, scrub, peeling, toner, serum, oogcrème, bb cream, foundation, concealer, poeder make-up, oogschaduw, eyeliner, lippenstift, lipgloss, rouge, wattenbolletjes, oorstokjes, haarborstel, kam, haarelastiekjes, haarspeldjes, föhn, scheerapparaat, scheermes, wegwerpscheermesjes, scheerkwast, baardolie, baardtrimmer, ontharingsstrips, waxstrips, epilator, nagelvijl, nagelknipper, pincet, deodorant spray, roller deodorant, antitranspirant, parfum, eau de toilette, bodyspray, bodywash, doucheolie, badolie, badzout, bruisballen, zeeppompje, handzeep navulling, desinfecterende handgel, handgel, lenzen, daglenzen, contactlenzen, leesbril, brillendoekjes, gehoorpropjes, oordopjes, condoom, zwangerschapstest, ovulatietest, thermometer, verband, gaasjes, elastisch verband, tape sport, blarenpleisters, likdoornpleisters, wratten middel, hoofdluismiddel, luizenshampoo, netenkam, keelsnoepjes, keeltabletten, hooikoortstabletten, antihistamine, slaaptabletten, melatonine, ijzertabletten, vitamine c, vitamine b12, zink, omega 3, glucosamine, probiotica, laxeermiddel, diarreeremmer, imodium, norit, maagzuurremmer, zuurbranden, rennie tabletten, sinaspril, ibuprofen 400, paracetamol 500, dafalgan, hansaplast, tena, tena lady, incontinentiemateriaal, kunstgebit tabletten, kukident, steradent, tongschraper, interdentale ragers, ragers, tandfloss, mondspoeling, listerine, elmex, parodontax, signal`],
];
for (const e of EXTRA2) RAW.push(e);

export const DICTIONARY: ReadonlyMap<string, CategoryId> = (() => {
  const m = new Map<string, CategoryId>();
  for (const [cat, text] of RAW) {
    for (const raw of text.split(',')) {
      const term = normalizeName(raw);
      if (term && !m.has(term)) m.set(term, cat);
    }
  }
  return m;
})();
